apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway
  labels:
    app: service-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-gateway
  template:
    metadata:
      labels:
        app: service-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "4000"
    spec:
      containers:
        - name: service-gateway
          image: lobao/service-gateway
          imagePullPolicy: Never
          resources:
            limits:
              memory: 256Mi
              cpu: "100m"
            requests:
              memory: 64Mi
              cpu: "100m"
          ports:
            - name: metrics
              protocol: TCP
              containerPort: 4000
          env:
            - name: PORT
              value: "4000"
