apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-users
  labels:
    app: service-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-users
  template:
    metadata:
      labels:
        app: service-users
    spec:
      containers:
        - name: service-users
          image: service-users:1.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: 32Mi
              cpu: "50m"
          requests:
            memory: 16Mi
            cpu: "10m"
          ports:
            - containerPort: 50051
          envFrom:
            - secretRef:
                name: service-users-secret
