apiVersion: v1
kind: Service
metadata:
  name: service-orders
spec:
  selector:
    app: service-orders
  ports:
    - name: grpc-server
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: metrics
      protocol: TCP
      port: 4000
      targetPort: 4000
