apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-cart
  labels:
    app: service-cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-cart
  template:
    metadata:
      labels:
        app: service-cart
    spec:
      containers:
        - name: service-cart
          image: lobao/service-cart
          imagePullPolicy: Never
          resources:
            limits:
              memory: 128Mi
              cpu: "100m"
            requests:
              memory: 64Mi
          ports:
            - containerPort: 50051
          envFrom:
            - secretRef:
                name: service-cart-secret
