apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-products
  labels:
    app: service-products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-products
  template:
    metadata:
      labels:
        app: service-products
    spec:
      containers:
        - name: service-products
          image: lobao/service-products
          imagePullPolicy: Never
          resources:
            limits:
              memory: 128Mi
              cpu: "100m"
            requests:
              memory: 64Mi
          ports:
            - containerPort: 50051
          envFrom:
            - secretRef:
                name: service-products-secret
