apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-products
  labels:
    app: service-products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-products
  template:
    metadata:
      labels:
        app: service-products
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "4000"
    spec:
      containers:
        - name: service-products
          image: lobao/service-products
          imagePullPolicy: Never
          resources:
            limits:
              memory: 128Mi
              cpu: "100m"
            requests:
              memory: 64Mi
          ports:
            - name: grpc-server
              protocol: TCP
              containerPort: 50051
            - name: metrics
              protocol: TCP
              containerPort: 4000
          envFrom:
            - secretRef:
                name: service-products-secret
