apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  labels:
    app: service-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
    spec:
      containers:
        - name: service-auth
          image: service-auth:1.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: 32Mi
              cpu: "50m"
          requests:
            memory: 16Mi
            cpu: "10m"
          ports:
            - containerPort: 50051
          envFrom:
            - secretRef:
                name: service-auth-secret
