apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  labels:
    app: service-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
    spec:
      containers:
        - name: service-auth
          image: lobao/service-auth
          imagePullPolicy: Never
          resources:
            limits:
              memory: 128Mi
              cpu: "100m"
            requests:
              memory: 64Mi
          ports:
            - containerPort: 50051
          envFrom:
            - secretRef:
                name: service-auth-secret
